spring:
  application:
    name: students_and_courses

  datasource:
    url: jdbc:postgresql://localhost:5435/students_db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    open-in-view: true

management:
  endpoints:
    access:
      default: none

