spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/bank?charset=utf8
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: db.changelog/db.changelog-master.xml

  cache:
    type: simple
    cache-names: clients,accounts,transactions
    redis:
      time-to-live: 1800000
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    persist-authorization: true
    filter: true
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

logging:
  level:
    org.springframework.security: DEBUG
    com.example.brokerapp: DEBUG

kafka:
  bootstrap:
    server: localhost:9092
  consumer:
    group-id: transaction-group
  topics:
    transactionTopic: big-transactions

server:
  port: 8090
