spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/broker_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

logging:
  level:
    org.springframework.security: DEBUG
    com.example.brokerapp: DEBUG


server:
  port: 8090
