spring:
  application:
    name: orders

  datasource:
    url: jdbc:postgresql://localhost:5435/orders_db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  health:
    db:
      enabled: true
    diskspace:
      path: /
      threshold: 100000000
  endpoint:
    health:
      show-components: always
      show-details: always

